### ISSUE TITLE
chainAfter return values

### ISSUE THREAD

**Issue by xblox** [uhop/dcl#22] opened 2016-04-28 18:35 UTC
Hi Eugene,
I am not sure this is out of scope for dcl or its even part of the AOP practice, but might it be possible to get the returning values from within the chain? For instance when I have 3 childs, calling each startup via chainAfter, I want the return value from the previous child call. I know I could do this with the OOP approach (super)  but I'd love to have this for chainAfter. I am aware this might add undesired effects but I'd be happy to know your thoughts first. Simple close this here, if not.
thanks a lot.

**Comment by uhop** [comment] 2016-05-03 22:25
This is a totally valid point. Preparing for 2.0 I am open to introduce incompatibilities, if they are warranted. I am struggled with "after" advices the same way, and I didn't come to a definitive conclusion. I will keep this ticket open, so I can collect some input on this topic, and possible solutions.

**Comment by gbaumgart** [comment] 2016-05-10 23:59
i am sure there must be something which takes an ordered list of functions and connects their outputs to its next's inputs. just realize I would need the same for chaining events better (so its horizontal or vertical).

anyhow, lodash is suppose to be good in that things, just can't recall what it was.

**Comment by uhop** [comment] 2016-06-27 19:49
BTW, can you give use cases for this functionality? I am working on dcl 2.0, and in order to implement it right, I want to consider typical use cases.

**Comment by gbaumgart** [comment] 2016-06-27 21:01
the only one i have is: giving noob users easier access to the result of super, including myself; and getting access to each chain call's result from withing somewhere below the next's chain call.

Currently, I placed in my end-user APIs some 'after chains' and in my most bottom low-level (system) classes I want to get the user's results. I checked the code and indeed is doing a void somewhere for chainAfter.

not sure its even possible though. i really hope this make sense.

g

**Comment by uhop** [comment] 2016-07-05 15:34
dcl 2 will come with custom weavers (in dev2.0 for now). Such weavers can implement what you want. The problem is, making a weaver looks involved now. I'll try to simplify it. At the very least I can provide a weaver like that as an example.

**Comment by gbaumgart** [comment] 2016-07-05 16:01
Hey, sounds good! Do you refer to ['aspect weavers'](https://en.wikipedia.org/wiki/Aspect_weaver) ?

**Comment by uhop** [comment] 2016-07-05 16:13
Yep, in a sense, it is an aspect weaver's implementation. `dcl 1` has them too, but for compactness they are built-in and not exposed to end users. `dcl 2` has them as explicit entities open for end users to modify and create.

To be honest, I hope people would rarely use this facility, because as any meta-programming facilities they are easy to abuse, make things obscure, and hard to debug. Yet, if you need them, there is no substitute. ;-)

**Comment by gbaumgart** [comment] 2016-07-05 16:15
thanks a lot, 
I gonna try as soon you have an example :+1:

**Comment by uhop** [comment] 2017-06-10 17:04
Addressed in 2.0.

**Closed by uhop** 2017-06-10 17:04 UTC
Labels: enhancement
